### The last line of this program has a GridSearch, that includes incompatible N-Gram parameters!

In [1]:
import numpy as np

In [126]:
# Import python libraries

import numpy as np
import pandas as pd
import os
import re

In [127]:
# Import dependencies

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# **CountVectorizer**

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# COUNT VECTORIZER TAKES AN ARRAY OF TEXT DATA, WHICH CAN BE DOCUMENTS OR SENTENCES AND CONSTRUCTS THE BAG-OF-WORDS MODEL FOR US
# Note CountVectorizer is an  instance of some type. We need to initialize that instance first before we apply the .fit_transform(docs) Alemi 04/07/2020
count=CountVectorizer()


In [4]:
import numpy as np 
# Note there are 4 lines in Docs which is really 3 documents. Each document is separated by a ",". So the frequency of occurance for the word "is" = 3 for the 3rd document
# 1 for the first and 1 for the second document. The word "is" occurs max = 3. It also occurs in every document. 
docs = np.array(['The sun is shining on Zhongping',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet,'
                 'and one and one is two'])


In [5]:
# Transforming Words into Feature Vectors 
bag = count.fit_transform(docs)

In [6]:
print(count.vocabulary_)

{'the': 7, 'sun': 5, 'is': 1, 'shining': 4, 'on': 2, 'zhongping': 10, 'weather': 9, 'sweet': 6, 'and': 0, 'one': 3, 'two': 8}


In [7]:
# Each index position in the feature vectors shown here corresponds to the integer values that are stored as dictionary items in the CountVectorizer vocabulary
# For example, the first feature at index position 0 resembles the count of the word 'and' which only occurs in the last document. Zhongping occurs on index 10,
# recall our index starts with zero, and it (Zhongping) only occurs once! in the first document. We call these feature vectors: Raw Term Frequencies: tf(t,d) -
# the number of times a term t occurs in a document d. The sequence of items in the bag-of-words model we just created is also called the 1-gram or unigram model -
# Each item or token in the vocabulary represents a single word. More generally, the contigious sequences of items in NLP - words, letters, or symbols - are also called
# n-grams. 
# In 1-gram, we will have 1-gram: "The", "Sun", "is", "Shining"
# In 2-gram: "The sun", "Sun is", "is Shining"
# We could have initialized our CountVectorizer instance with ngram_range=(2,2)
print(bag.toarray())

[[0 1 1 0 1 1 0 1 0 0 1]
 [0 1 0 0 0 0 1 1 0 1 0]
 [2 3 0 2 1 1 1 2 1 1 0]]


In [8]:
# Let us capture the inverse of document frequency: idf(t,d) = log n/(1+df(d,t)) - where n is the number of our documents. Log is a weight and f(d,t) was explained before!
# Another transformer from scikit-learn library is TfidTransformer class, that takes the term frequencies from CountVectorizer class as input and transforms them into tf-idfs
!pip show tensorflow


Name: tensorflow
Version: 2.1.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/piruzalemi/opt/anaconda3/lib/python3.7/site-packages
Requires: numpy, astor, six, wheel, wrapt, tensorboard, gast, google-pasta, opt-einsum, protobuf, keras-applications, termcolor, scipy, tensorflow-estimator, keras-preprocessing, absl-py, grpcio
Required-by: 


In [9]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -q -U libarchive
import libarchive

/bin/sh: apt-get: command not found


In [10]:
# from sklearn.feature_extraction.text import TfidTransformer
!apt-get -qq install -y libfluidsynth1

/bin/sh: apt-get: command not found


In [11]:
#from sklearn.feature_extraction.text import TfidTransformer
!pip install tf-nightly

In [12]:
#from sklearn.feature_extraction.text import TfidTransformer
from sklearn.feature_extraction.text import TfidfTransformer

In [13]:
#  Tf is “n” (natural) by default, “l” (logarithmic) when sublinear_tf=True. 
#  Idf is “t” when use_idf is given, “n” (none) otherwise. 
#  Normalization is “c” (cosine)
#  when norm='l2', “n” (none) when norm=None.
tfidf = TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)

In [14]:
np.set_printoptions(precision=2)

In [15]:
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.3  0.51 0.   0.39 0.39 0.   0.3  0.   0.   0.51]
 [0.   0.43 0.   0.   0.   0.   0.56 0.43 0.   0.56 0.  ]
 [0.5  0.45 0.   0.5  0.19 0.19 0.19 0.3  0.25 0.19 0.  ]]


In [16]:
# The word 'is' has a frequency of 3 (tf=3) in the third document, and the document frequency of this term is also 3 since the term "is" occurs in all three documents (df=3)
#. Thus, we can calculate  the inverse document frequency as follows: idf("is",d3) = log(1+3)/(1+3) = 0, and the tf-idf (termFrequency-inverseDocumentFrequency) 
#  tf-idf("is",d3)=3 * (0+1) =3. Note this value is different than the above derived tf-idf(d3), as the above values in the final step is L2-normalized.
# lets clean our data by excluding unwanted characters!

In [17]:
#import pyprind
import tarfile
!pip install -q matplotlib-venn

In [18]:
#with tarfile.open('https://www.kaggle.com/aaron7sun/stocknews#Combined_News_DJIA.csv') as tar:
#  tar.extractall()
import numpy as np

In [19]:
np.random.seed(0)
!pip install pyprind
import pyprind
import pandas as pd
import os

# **Access Kaggle**


In [20]:
# Install Kaggle library
!pip install -q kaggle
!pip install kaggle

In [21]:
#!mkdir ~/.kaggle
#!cp Downloads/kaggle.json ~/.kaggle/kaggle.json

In [22]:
!kaggle datasets download -d aaron7sun/stocknews

stocknews.zip: Skipping, found more recently modified local copy (use --force to force download)


In [23]:
!kaggle datasets download -d aaron7sun/stocknews

stocknews.zip: Skipping, found more recently modified local copy (use --force to force download)


In [24]:
ls

Alemi2_final_project.ipynb
Combined_News_DJIA.csv*
Combined_News_DJIA.xls
D11ScikitLearnBayes.pdf
Final_NLTK_Latent.ipynb
Linear_Visualization_Graph.ipynb
Naive_Visualization_Graph-Copy1.ipynb
Naive_Visualization_Graph.ipynb
RedditNews.csv*
TensorFlow.ipynb
Tony Holdroyd - Tensorflow 2.0 Quick Start Guide (2019, Packt Publishing).pdf
Untitled.ipynb
alemi2_NLTK.ipynb
alemi_NLTK.ipynb
alemi_final_project-Copy1.ipynb
alemi_final_project.ipynb
alemi_final_project2.ipynb
kaggle.json
plot_logistic.ipynb
report.txt
stocknews/
stocknews.zip
upload_DJIA_table.csv*


In [25]:
#pd.read_csv("stocknews/RedditNews.csv")
#!unzip stocknews.zip -d ~/.kaggle

In [26]:
#df=pd.read_csv('stocknews.zip', compression='zip', header=0, sep=',', quotechar='"')
rNews=pd.read_csv('RedditNews.csv')
rNews.head()


Date                                               News
0  2016-07-01  A 117-year-old woman in Mexico City finally re...
1  2016-07-01   IMF chief backs Athens as permanent Olympic host
2  2016-07-01  The president of France says if Brexit won, so...
3  2016-07-01  British Man Who Must Give Police 24 Hours' Not...
4  2016-07-01  100+ Nobel laureates urge Greenpeace to stop o...

In [27]:
dNews=pd.read_csv('Combined_News_DJIA.csv')
dNews.head()

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2  2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-14      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

In [28]:
# we need to clean yje "'" and \ and all punctuation marks like b" which are HTML makups
# to accomplish this, we will use Python's regular expression (regex) library re as shown below
import re


In [29]:
# We will remove all the non-word characters from the text via the regex [\w] + and convert the text into lower characters
def preprocessor(text):
    
    text = (re.sub('[\W]+',' ', text.lower() + ''))
    text = re.sub("b ",' ',text)
    return text

In [30]:
dNews['Top1'] = dNews['Top1'].apply(preprocessor)

In [31]:
dNews['Top1'].head()

0     georgia downs two russian warplanes as countr...
1     why wont america and nato help us if they won...
2     remember that adorable 9 year old who sang at...
3     u s refuses israel weapons to attack iran rep...
4     all the experts admit that we should legalise...
Name: Top1, dtype: object

In [32]:
dNews.loc[0,'Top1'][0:]

' georgia downs two russian warplanes as countries move to brink of war '

# **Tokenization**

In [33]:
def tokenizer(text):
  return text.split()


In [34]:
tokenizer(dNews['Top1'][0])

['georgia',
 'downs',
 'two',
 'russian',
 'warplanes',
 'as',
 'countries',
 'move',
 'to',
 'brink',
 'of',
 'war']

In [35]:
# install NTLK see www.ntlk.org/book/ in advanced applications in NLP
#  We will use Porter stemmer's algorim - 1979, which is word stemming
!pip install nltk

In [36]:
from nltk.stem.porter import PorterStemmer

In [37]:
porter = PorterStemmer()

In [38]:
def tokenizer_porter(text):
  return [porter.stem(word) for word in text.split()]

In [39]:
tokenizer_porter(dNews['Top1'][0])

['georgia',
 'down',
 'two',
 'russian',
 'warplan',
 'as',
 'countri',
 'move',
 'to',
 'brink',
 'of',
 'war']

In [40]:
# Stopwords are simply those words that are extremely common but bear no use for our analysis!
# like is, and, has, like,,,, we will use 127 stopwords already available in the NTLK library which we get by downloading it
import nltk


In [41]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/piruzalemi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [42]:
# Load and apply the stopwards after download
from nltk.corpus import stopwords

In [43]:
stop = stopwords.words('english')

In [44]:
[w for w in tokenizer_porter(dNews['Top1'][0]) if w not in stop]

['georgia', 'two', 'russian', 'warplan', 'countri', 'move', 'brink', 'war']

In [45]:
# Training a logistic regression model for Document Classification
# Here we train a logistic 

# **Training a Logistic Regression on Document Classification - Alemi 04/07/2020**



In [46]:
# we will use 
dNews.head()

Date  Label                                               Top1  \
0  2008-08-08      0   georgia downs two russian warplanes as countr...   
1  2008-08-11      1   why wont america and nato help us if they won...   
2  2008-08-12      0   remember that adorable 9 year old who sang at...   
3  2008-08-13      0   u s refuses israel weapons to attack iran rep...   
4  2008-08-14      1   all the experts admit that we should legalise...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

In [47]:
#. This should run on cleaned data, Note i have solely cleaned only row [0], we have to run the above code on all rows!!!!!!!
#. So this code is solely is for a placeholder, after the data is fully cleaned, then we run this part...Alemi 04/07/2020
X_train = dNews.loc[:1000,"Top1"].values

In [48]:
y_train= dNews.loc[:1000,"Label"].values

In [49]:
X_test = dNews.loc[1001:,"Top1"].values

In [50]:
y_test= dNews.loc[1001:,"Label"].values

In [51]:
# like our class exercise we run the GridSearch to find the optimal set of parameters
from sklearn.model_selection import GridSearchCV

In [52]:
from sklearn.pipeline import Pipeline

In [53]:
from sklearn.linear_model import LogisticRegression

In [129]:
from sklearn.ensemble import RandomForestClassifier

In [130]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [131]:
tfidf = TfidfVectorizer(strip_accents=None,lowercase=False,preprocessor=None)

# Clean The Data

In [132]:
import re

In [133]:
def preprocessor(text):
  text=(re.sub('[\W]+', ' ', text.lower()))
  return text

In [134]:
dNews['Top1'] = dNews['Top1'].apply(preprocessor)

In [135]:
dNews['Top1']

0        georgia downs two russian warplanes as countr...
1        why wont america and nato help us if they won...
2        remember that adorable 9 year old who sang at...
3        u s refuses israel weapons to attack iran rep...
4        all the experts admit that we should legalise...
                              ...                        
1984    barclays and rbs shares suspended from trading...
1985    2 500 scientists to australia if you want to s...
1986                     explosion at airport in istanbul
1987    jamaica proposes marijuana dispensers for tour...
1988    a 117 year old woman in mexico city finally re...
Name: Top1, Length: 1989, dtype: object

In [136]:
#import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/piruzalemi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [137]:
from nltk.corpus import stopwords

In [138]:
stop=stopwords.words('english') + [None]

In [139]:
tokenizer_porter(dNews['Top1'][0])

['georgia',
 'down',
 'two',
 'russian',
 'warplan',
 'as',
 'countri',
 'move',
 'to',
 'brink',
 'of',
 'war']

In [140]:
[w for w in tokenizer_porter(dNews['Top1'][0]) if w not in stop]

['georgia', 'two', 'russian', 'warplan', 'countri', 'move', 'brink', 'war']

# **Transforming words into feature vectors**

In [141]:
from sklearn.feature_extraction.text import CountVectorizer

In [142]:
#count=CountVectorizer

In [143]:
#docs=np.array(dNews['Top1'])

In [144]:
vectorizer = TfidfVectorizer()

In [145]:
# This is my bag of words based on the word count in the respective document, takes an array of texts and counts its words
bag=vectorizer.fit_transform(dNews['Top1'])
print(vectorizer.vocabulary_)
bag.shape


{'georgia': 3128, 'downs': 2320, 'two': 7224, 'russian': 6100, 'warplanes': 7524, 'as': 660, 'countries': 1790, 'move': 4660, 'to': 7046, 'brink': 1116, 'of': 4910, 'war': 7513, 'why': 7624, 'wont': 7682, 'america': 509, 'and': 530, 'nato': 4740, 'help': 3390, 'us': 7360, 'if': 3579, 'they': 6985, 'now': 4858, 'did': 2161, 'we': 7555, 'them': 6976, 'in': 3636, 'iraq': 3835, 'remember': 5868, 'that': 6971, 'adorable': 372, 'year': 7742, 'old': 4934, 'who': 7616, 'sang': 6149, 'at': 700, 'the': 6973, 'opening': 4955, 'ceremonies': 1359, 'was': 7531, 'fake': 2754, 'too': 7065, 'refuses': 5818, 'israel': 3859, 'weapons': 7561, 'attack': 712, 'iran': 3831, 'report': 5898, 'all': 470, 'experts': 2687, 'admit': 364, 'should': 6375, 'legalise': 4120, 'drugs': 2362, 'mom': 4605, 'missing': 4578, 'gay': 3104, 'man': 4344, 'bad': 788, 'he': 3357, 'not': 4849, '21': 102, 'cheerleader': 1408, 'then': 6978, 'still': 6656, 'be': 856, 'looking': 4252, 'for': 2957, 'him': 3427, 'an': 525, 'afghan': 396

(1989, 7783)

In [146]:
bag.shape

(1989, 7783)

In [147]:
print(bag.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [148]:
bagArray=bag.toarray()

In [149]:
bagArray.shape

(1989, 7783)

In [150]:
from sklearn.feature_extraction.text import TfidfTransformer

In [151]:
tfidf=TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)

In [152]:
np.set_printoptions(precision=2)

In [153]:
# TfidTransformer class, takes the raw term frequencies from TfidVectorizer class as input and transforms them into tf-idfs
print(tfidf.fit_transform(vectorizer.fit_transform(dNews['Top1'])).toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [154]:
# X_train = dNews.loc[:1000,"Top1"].values
X1 = dNews.loc[:,"Top1"].values
y1 = dNews.loc[:,"Label"].values
X2 = dNews.loc[:,"Top2"].values
y2 = dNews.loc[:,"Label"].values
X3 = dNews.loc[:,"Top3"].values
y3 = dNews.loc[:,"Label"].values
X = np.concatenate((X1, X2, X3))
y = np.concatenate((y1, y2, y3))
print(X.shape)
print(y.shape)

(5967,)
(5967,)


In [155]:
vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(2,2))

In [156]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)
#.   
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [157]:
X_train.shape

(2983, 29910)

In [158]:
X_test.shape

(2984, 29910)

In [159]:
param_grid =[{'vect__ngram_range': [(1,1)],
              'vect__stop_words': [stop, None],
              'vect__topkenizer': [tokenizer,tokenizer_porter],
              'clf__penalty':['l1','l2'],
              'clf__C':[1.0,10.0]}]
              

In [160]:
lr_tfidf = Pipeline([('vect',tfidf),('clf',LogisticRegression(random_state=0))])

In [165]:
#lr_tfidf = Pipeline([('vect',tfidf),('clf',RandomForestClassifier(random_state=0))])

In [166]:
gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, scoring='accuracy', cv=5, verbose=1, n_jobs=1)

In [167]:
for param in lr_tfidf.get_params().keys():
    print(param)

memory
steps
verbose
vect
clf
vect__norm
vect__smooth_idf
vect__sublinear_tf
vect__use_idf
clf__bootstrap
clf__class_weight
clf__criterion
clf__max_depth
clf__max_features
clf__max_leaf_nodes
clf__min_impurity_decrease
clf__min_impurity_split
clf__min_samples_leaf
clf__min_samples_split
clf__min_weight_fraction_leaf
clf__n_estimators
clf__n_jobs
clf__oob_score
clf__random_state
clf__verbose
clf__warm_start


In [168]:
gs_lr_tfidf.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


ValueError: Invalid parameter C for estimator RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators='warn',
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False). Check the list of available parameters with `estimator.get_params().keys()`.